/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData auction = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData race1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guild = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData race2 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
